### ISSUE TITLE
Proposal: add hints when pulling detailed information from Internet

### ISSUE THREAD

**Issue by xiongnemo** [iabtw/OCSysInfo#17]
I have a normal or maybe poor Internet connection, so it stuck here with no hints:

![image](https://user-images.githubusercontent.com/38759782/153708473-d77a0e41-08d9-45b7-aa5a-c7a1cfe42a40.png)

Maybe it's better to add some flashing words indicating which phase the script is working on?

**Comment by iabtw** [comment]
I don't personally see much purpose behind this, as we already have a Logger that dumps it all to an `ocsysinfo.log` file. 

However, @Mahas1 does deem this useful enough to be implemented in. They'll soon push changes which solve this issue.

Once they do, I will close this issue, unless further action is needed; i.e. bugs with the latest changes, improper implementation, etc.

**Comment by Mahas1** [comment]
Implemented this in the latest commit. Will close this issue for now.
